<?php

/**
* Implements hook_theme
*/
function dragon_theme($existing, $type, $theme, $path) {
  return [
    'dragon_breakpoint_form' => [
      'render element' => 'form',
      'template' => 'dragon-breakpoint-form'
    ],
    'dragon_builder' => [
      'variables' => [
        'content' => NULL,
      ],
      'template' => 'dragon-builder'
    ],
  ];
}



/**
* Implements hook_preprocess_field
*/
function dragon_preprocess_field(&$vars) {
  $vars['attributes']['gjs-field-id'] = $vars['field_name'];
  $vars['attributes']['gjs-field-type'] = $vars['field_type'];
}

/**
* hook_preprocess_menu
*/
function dragon_preprocess_menu(&$vars) {
  $vars['attributes']['gjs-menu-id'] = $vars['menu_name'];
}

/**
* Implements hook_preprocess_region
*/
function dragon_preprocess_region(&$vars) {
  $vars['attributes']['gjs-region-id'] = $vars['region'];

  $path = \Drupal::service('path.current')->getPath();
  $path_args = explode('/', $path);
  $a = array_shift($path_args);

  $suggestions = ['region'] + theme_get_suggestions($path_args, 'region', '--');
  $region_id_suggestions = [];
  foreach($suggestions as $id => $suggestion) {
    $region_id_suggestions[] = "{$suggestion}--{$vars['region']}";
  }
  $vars['#attached']['drupalSettings']['dragon']['theme']['suggestions']['regions'][$vars['region']] = array_merge($suggestions, $region_id_suggestions);
}

/**
* Implements hook_preprocess_page
*/
function dragon_preprocess_page(&$vars) {

  // Add in our core libraries.
  $vars['#attached']['library'][] = 'dragon/builder';
  $vars['#attached']['library'][] = 'dragon/grapesjs-preset-webpage';
  $vars['#attached']['library'][] = 'dragon/grapesjs-aviary';
  $vars['#attached']['library'][] = 'dragon/grapesjs-navbar';
  $vars['#attached']['library'][] = 'dragon/grapesjs-ckeditor';
  $vars['#attached']['library'][] = 'dragon/grapesjs-export';
  $vars['#attached']['library'][] = 'dragon/grapesjs-filestack';
  $vars['#attached']['library'][] = 'dragon/grapesjs-forms';
  $vars['#attached']['library'][] = 'dragon/grapesjs-countdown';
  $vars['#attached']['library'][] = 'dragon/grapesjs-blocks-basic';

  $theme_info = \Drupal::service('theme.manager')->getActiveTheme();

  $vars['#attached']['drupalSettings']['dragon']['theme'] = [
    'name' => $theme_info->getName(),
    'engine' => $theme_info->getEngine(),
    'libraries' => $theme_info->getLibraries(),
    'regions' => $theme_info->getRegions(),
  ];

  $path = \Drupal::service('path.current')->getPath();
      $path_args = explode('/', $path);
      $a = array_shift($path_args);

  $vars['#attached']['drupalSettings']['dragon']['theme']['suggestions'] = [
    'page' => ['page'] + theme_get_suggestions($path_args, 'page', '--'),
  ];
}

/**
* Implements hook_entity_view_alter.
*/
function dragon_entity_view_alter(array &$build, Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display) {
  $build['#attributes']['gjs-entity-type'] = $build['#entity_type'];
  // $build['#attributes']['gjs-entity-bundle'] = $build[$build['#entity_type']]->bundle();
}
